#!/bin/bash
# shellcheck disable=SC1090

# depends yarn

CONFIG_SRC_DIR=~/Documents/configuration/src
VIM_RECIPE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

shef apt vim-gnome

if [ ! -d "$CONFIG_SRC_DIR/.vim" ];then
    git clone https://github.com/CaptainQuirk/.vim.git "$CONFIG_SRC_DIR/.vim"
fi

if [ ! -d "$HOME/.vim" ]; then
    ln -s "$CONFIG_SRC_DIR/.vim" "$HOME/.vim"
fi

cd "$CONFIG_SRC_DIR/.vim" || exit 1
git pull

git submodule update --init --recursive

for SUBMODULE in $CONFIG_SRC_DIR/.vim/bundle/*; do
    cd "$SUBMODULE" || exit 1

    if [ ! -d "$SUBMODULE/.git" ] && [ ! -f "$SUBMODULE/.git" ]; then
        echo -e "$SUBMODULE is not a submodule. Nothing to do."
        continue
    fi

    echo -e "Checking out master branch"
    git checkout master

    NAME=$(basename "$SUBMODULE")
    echo -e "Updating remote references for submodule $NAME"
    git remote update

    echo -e "Compare master and remote origin master"
    LOCAL=$(git rev-parse master)
    REMOTE=$(git rev-parse origin/master)

    if [ "$LOCAL" = "$REMOTE" ]; then
        echo -e "Remote and local are the same. Nothing to do."
        cd - || exit 2
        continue
    fi

    BASE=$(git merge-base master origin/master)
    if [ "$REMOTE" = "$BASE" ]; then
        echo -e "Local is ahead. Weird. Ignoring"
        cd - || exit 2
        continue
    fi

    if [ "$LOCAL" != "$BASE" ]; then
        echo -e "Local and remote have diverged. Really Weird. Ignoring"
        cd - || exit 2
        continue
    fi

    echo -e "Remote is ahead. Choose an option below"

    OK=0
    while [ "$OK" -eq 0 ]
    do
      read -p "Would you like to Pull changes from remote, Browse remote changes, or skip? (P/B/S) " OPT;
      REMOTE_URL="$(git remote -v | grep fetch | head -1 | cut -f2 | cut -d' ' -f1 | sed -e's/git@/http:\/\//' -e's/\.git$//' | sed -E 's/(\/\/[^:]*):/\1\//')"
      REMOTE_URL+="/compare/$BASE...master"
      case "$OPT" in
          P ) echo -e "Merging origin/master in master"; git stash; git merge master origin/master; OK=1; break;;
          B ) xdg-open "$REMOTE_URL" >/dev/null;;
          S ) OK=1; break;;
      esac
    done

    cd - || exit 2
done

for file in $VIM_RECIPE_PATH/plugins/*; do
    source "$file"
done


# V wrapper
# --------

sudo cp --update "$VIM_RECIPE_PATH/files/v" /usr/local/bin


# DEPENDENCIES
# ------------

# AG
shef brew the_silver_searcher

# Livedown
yarn global add install livedown

# eclim
# For the moment, the installation is not fully automated
# @link http://eclim.org/install.html#unattended-automated-install

# # Download installer
# wget https://github.com/ervandew/eclim/releases/download/2.7.0/eclim_2.7.0.jar -P $CACHE_DIR

# # Download eclipse
# wget http://ftp.fau.de/eclipse/eclipse/downloads/drops4/R-4.7-201706120950/eclipse-platform-4.7-linux-gtk-x86_64.tar.gz -P $CACHE_DIR

# tar -zxf $CACHE_DIR/org.eclipse.jdt-4.7.zip
# sudo mv $CACHE_DIR/eclipse /opt

# Write template string to create .desktop file in /usr/share

# # Download jdt
# wget http://ftp.fau.de/eclipse/eclipse/downloads/drops4/R-4.7-201706120950/org.eclipse.jdt-4.7.zip -P $CACHE_DIR
# unzip $CACHE_DIR/org.eclipse.jdt-4.7.zip -d jdt
# sudo cp jdt/plugins/* /opt/eclipse/plugins/*
# sudo cp jdt/features/* /opt/eclipse/features/*

